version: '2.2'

networks:
    public:
        driver: bridge

services:
  php-cli:
      build:
        context: .
        dockerfile: ./docker/images/php-7.1-cli
      networks:
        - public
      volumes:
        - ./:/var/www/html:cached
      command: tail -f /dev/null